language: rust
cache: cargo
sudo: false
rust:
    - nightly
env:
    - RUST_BACKTRACE=1

before_script:
    - cargo install wasm-pack
script:
    - cd closest-pair && cargo test
after_success:
    - ./scripts/travis-deploy.sh
