language: rust
cache: cargo
sudo: false
rust:
    - nightly
env:
    - RUST_BACKTRACE=1

before_script:
    - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
    - nvm install 10 && nvm use 10
script:
    - (cd closest-pair && cargo test)
after_success:
    - ./scripts/travis-deploy.sh
